[package]
name = "read_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes_macro = { path = "../bytes_macro" }

[dev-dependencies]

