[package]
name = "uka_shiori"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.40"
tokio = { version = "1.29.1", features = ["full"] }
uka_util = { path = "../uka_util" }

[dev-dependencies]
anyhow = "1.0.71"
rstest = "0.18.1"
