[package]
name = "uka_sstp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.52"
uka_util = { path = "../uka_util" }

[dev-dependencies]
anyhow = "1.0.77"
rstest = "0.18.2"
