name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: "-D warnings"
      CARGO_INCREMENTAL: 0
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.os }}-stable20230820
      - name: Cargo build
        run: cargo test --no-run
      - name: Clear the cargo caches
        shell: bash
        run: |
          cargo install cargo-cache --version 0.8.3 --no-default-features --features ci-autoclean
          cargo-cache

  test:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: "-D warnings"
      RUST_BACKTRACE: full
      CARGO_INCREMENTAL: 0
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.os }}-stable20230820
      - name: Cargo test
        run: cargo test

  examples:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: "-D warnings"
      RUST_BACKTRACE: full
      CARGO_INCREMENTAL: 0
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.os }}-stable20230820
      - run: |
          for example in */examples/*.rs
          do
              cargo run --example "$(basename "${example%.rs}")" -- $args
          done

  lint:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.os }}-stable20230820
      - name: Cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --tests --examples --all-features

