name: PR Agent

on:
  pull_request:
  issue_comment:

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: Run pr agent on every pull request, respond to user comments
    if: github.event.comment.user.login == 'k-kinzal'
    steps:
      - name: PR Agent action step
        id: pragent
        uses: k-kinzal/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
